"""guaaboutpage 1 column deleted

Revision ID: 114500cb5629
Revises: 7199926a2e4b
Create Date: 2021-01-12 02:27:31.003848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114500cb5629'
down_revision = '7199926a2e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AboutPage', 'banner_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AboutPage', sa.Column('banner_img', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
