"""unique deleted

Revision ID: 1a06619ffb21
Revises: bf92c94dd0a8
Create Date: 2020-12-27 17:26:21.716860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a06619ffb21'
down_revision = 'bf92c94dd0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AboutPage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_img', sa.String(length=20), nullable=False),
    sa.Column('main_text', sa.String(length=100), nullable=True),
    sa.Column('second_img', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AdmissionStage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_img', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Advantage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('svg_img', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BannerImg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(length=50), nullable=False),
    sa.Column('banner_img', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_img', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Package')
    op.drop_table('BannerImg')
    op.drop_table('Advantage')
    op.drop_table('AdmissionStage')
    op.drop_table('AboutPage')
    # ### end Alembic commands ###
