"""aboutpage model updated

Revision ID: 1b64ddf11690
Revises: f7bcc3ef718f
Create Date: 2020-12-24 22:27:20.779678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b64ddf11690'
down_revision = 'f7bcc3ef718f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AboutPage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_img', sa.String(length=20), nullable=False),
    sa.Column('main_text', sa.String(length=100), nullable=False),
    sa.Column('second_img', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AboutPage')
    # ### end Alembic commands ###
