"""packages updated

Revision ID: 4c5e586b04f6
Revises: a7dd1ba72396
Create Date: 2021-01-12 12:13:26.148524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5e586b04f6'
down_revision = 'a7dd1ba72396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Package', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Package', sa.Column('link', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###
