"""advantages model created

Revision ID: 5cc90cf8fc8d
Revises: 1b64ddf11690
Create Date: 2020-12-25 19:44:17.081237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc90cf8fc8d'
down_revision = '1b64ddf11690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Advantages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('svg_img', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Advantages')
    # ### end Alembic commands ###
