"""second

Revision ID: 73cd6e99c1b7
Revises: a143793e4659
Create Date: 2020-12-24 15:03:41.448524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cd6e99c1b7'
down_revision = 'a143793e4659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AboutPage', sa.Column('third_img', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AboutPage', 'third_img')
    # ### end Alembic commands ###
