"""aboutpage model updated

Revision ID: 7770d8521402
Revises: bd5c284e3b0d
Create Date: 2020-12-27 15:00:01.991787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7770d8521402'
down_revision = 'bd5c284e3b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AboutPage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_img', sa.String(length=20), nullable=False),
    sa.Column('main_text', sa.String(length=100), nullable=True),
    sa.Column('second_img', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AboutPage')
    # ### end Alembic commands ###
