"""some columns made unique

Revision ID: 77ba4213d0fa
Revises: 7770d8521402
Create Date: 2020-12-27 17:08:01.141601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ba4213d0fa'
down_revision = '7770d8521402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'AboutPage', ['banner_img'])
    op.create_unique_constraint(None, 'AboutPage', ['second_img'])
    op.create_unique_constraint(None, 'AdmissionStage', ['stage_img'])
    op.create_unique_constraint(None, 'Advantage', ['svg_img'])
    op.create_unique_constraint(None, 'BannerImg', ['page_name'])
    op.create_unique_constraint(None, 'BannerImg', ['banner_img'])
    op.create_unique_constraint(None, 'Package', ['pack_img'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Package', type_='unique')
    op.drop_constraint(None, 'BannerImg', type_='unique')
    op.drop_constraint(None, 'BannerImg', type_='unique')
    op.drop_constraint(None, 'Advantage', type_='unique')
    op.drop_constraint(None, 'AdmissionStage', type_='unique')
    op.drop_constraint(None, 'AboutPage', type_='unique')
    op.drop_constraint(None, 'AboutPage', type_='unique')
    # ### end Alembic commands ###
