"""admissionStage model created

Revision ID: 9fc8a3e26c7e
Revises: fb72b0747d99
Create Date: 2020-12-26 17:53:02.600781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc8a3e26c7e'
down_revision = 'fb72b0747d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AdmissionStage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_img', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AdmissionStage')
    # ### end Alembic commands ###
