"""Initial

Revision ID: a143793e4659
Revises: 4625491681d1
Create Date: 2020-12-24 15:02:21.897221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a143793e4659'
down_revision = '4625491681d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AboutPage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_img', sa.String(length=20), nullable=False),
    sa.Column('main_text', sa.String(length=100), nullable=False),
    sa.Column('second_img', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('QuestionAnswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('QuestionAnswer')
    op.drop_table('AboutPage')
    # ### end Alembic commands ###
