"""about table again create

Revision ID: b0225c6b0392
Revises: e3fa1a8d6130
Create Date: 2021-01-12 02:32:48.747097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0225c6b0392'
down_revision = 'e3fa1a8d6130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AboutPage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_text', sa.String(length=100), nullable=True),
    sa.Column('second_img', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AboutPage')
    # ### end Alembic commands ###
