"""packages updated

Revision ID: dc4261ac7717
Revises: 4c5e586b04f6
Create Date: 2021-01-12 12:15:19.192906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4261ac7717'
down_revision = '4c5e586b04f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_img', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('all_details', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Package')
    # ### end Alembic commands ###
