"""guaaboutpage 1 column deleted

Revision ID: e3fa1a8d6130
Revises: 114500cb5629
Create Date: 2021-01-12 02:30:51.699121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fa1a8d6130'
down_revision = '114500cb5629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AboutPage', 'banner_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AboutPage', sa.Column('banner_img', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
