"""aboutpage model updated

Revision ID: f7bcc3ef718f
Revises: 73cd6e99c1b7
Create Date: 2020-12-24 22:24:31.755039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bcc3ef718f'
down_revision = '73cd6e99c1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AboutPage', 'third_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AboutPage', sa.Column('third_img', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
