"""training package model created

Revision ID: fb72b0747d99
Revises: 29eb858a3073
Create Date: 2020-12-26 14:22:09.800273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb72b0747d99'
down_revision = '29eb858a3073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Advantage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('svg_img', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BannerImg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.String(length=50), nullable=False),
    sa.Column('banner_img', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_img', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Package')
    op.drop_table('BannerImg')
    op.drop_table('Advantage')
    # ### end Alembic commands ###
